name: AAA
channels:
  - conda-forge
  - defaults
  - apple
dependencies:
  - python=3.9
  - numpy
  - pandas
  - notebook
  - scikit-learn
  - matplotlib
  - seaborn
  - geopandas
  - shapely
  - ipython
  - tensorflow-deps
  - pip:
    - h3
    - tensorflow-macos
    - tensorflow-metal
