name: AAA
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - notebook
  - scikit-learn
  - matplotlib
  - seaborn
  - geopandas
  - shapely
  - ipython
  - pip:
    - h3
    - tensorflow
